# Numpy Arrays

In [172]:
import numpy as np

# Creating Arrays

In [173]:
data = [1, 2, 3, 4]
first_array = np.array(data)
first_array

array([1, 2, 3, 4])

In [174]:
data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

my_array = np.array(data)
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [176]:
np.zeros(3)

array([0., 0., 0.])

In [177]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
np.arange(3, 12, 4)

array([ 3,  7, 11])

# Dimensions and shape

In [179]:
one_d = np.arange(21)
one_d


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [180]:
one_d.shape

(21,)

In [181]:
one_d.ndim

1

In [182]:
one_d.size

21

In [183]:
list_of_lists = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

two_d = np.array(list_of_lists)
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
two_d.ndim

2

In [185]:
two_d.size

9

In [186]:
two_d.shape

(3, 3)

In [187]:
one_d = np.arange(12)
two_d = one_d.reshape(3, 4)
two_d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
two_d.shape

(3, 4)

In [189]:
two_d.ndim

2

In [190]:
two_d = two_d.reshape(2, 2, 3)
two_d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [191]:
two_d.shape

(2, 2, 3)

In [192]:
darray = np.arange(100, dtype=np.int8)
darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype=int8)

In [193]:
darray.dtype

dtype('int8')

In [194]:
darray.nbytes

100

# Broadcasting

In [196]:
A1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

A2 = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
])

In [198]:
A1 + A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [199]:
A1 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [200]:
A3 = np.array([1, 1, 1])
A3.shape

(3,)

In [202]:
A1 + A3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [203]:
A4 = np.arange(10).reshape(2, 1, 5)
A4

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [204]:
A5 = np.arange(14).reshape(2, 7, 1)
A5

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]]])

In [205]:
A6 = A4 + A5
A6.shape

(2, 7, 5)

# Matrix Operations

In [206]:
M1 = np.arange(9).reshape(3, 3)
M1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [208]:
M2 = np.arange(2, 11).reshape(3, 3)
M2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [209]:
M1.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [211]:
M1.diagonal()

array([0, 4, 8])

In [212]:
M1 @ M2

array([[ 21,  24,  27],
       [ 66,  78,  90],
       [111, 132, 153]])